#! /bin/sh

sxhkd &

bspc config border_width        2
bspc config window_gap         10 #26 is pretty good total gap
 
bspc config top_padding		   32 #bar gap is 16
bspc config bottom_padding	   16	
bspc config left_padding	   16
bspc config right_padding	   16

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true


#visual options
bspc config normal_border_color "#383036"
bspc config active_border_color "#689d6a"
bspc config focused_border_color "#ecb3ff"
#bspc config focused_border_color "#fe6b3f"
bspc config presel_border_color "#d43f10"
bspc config focused_locked_border_color "#cc24ad"

bspc rule -a Dmenu border=on
bspc rule -a lemonbar border=on 

#monitors
bspc monitor -d I II III IV V 

bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

sh ~/bin/bar.sh &
